### ISSUE TITLE
Should we remove redirect rules for editing and deleting entries?

### ISSUE THREAD

**Issue by zackkatz** [gravityview/Dashboard-Views#6]
I think it makes sense to remove `delete_redirect_url` and `edit_redirect_url` when displaying an entry in the admin.

Thoughts?

**Comment by rafaehlers** [comment]
Why? Do you fear this can be used as an XSS entry point or something similar?

**Comment by zackkatz** [comment]
No, because if you’re in the admin, wouldn’t you want different rules?

**Comment by zackkatz** [comment]
Closing: if they want, they can clone a View and add admin-specific redirects.
